# SPDX-License-Identifier: BSD-3-Clause

# Define the custom test suite configurations
hello_world:
  msg: A custom hello world to you!
# single_core_forward_perf:
#   test_parameters: # Add frame size / descriptor count combinations as needed
#     - frame_size: 64
#       num_descriptors: 512
#       expected_mpps: 1.0 # Set millions of packets per second according to your devices expected throughput for this given frame size / descriptor count
#     - frame_size: 64
#       num_descriptors: 1024
#       expected_mpps: 1.0
#     - frame_size: 512
#       num_descriptors: 1024
#       expected_mpps: 1.0
#   delta_tolerance: 0.05
